# Site Settings
title: Start Jekyll
email: ngocvu@gmail.com
description: >
  A guide to getting started with Jekyll.
baseurl: ""
url: "http://ngocvu3010.github.io"
twitter_username: ngocvu
github_username:  ngocvu
# Build Settings
sass:
  sass_dir: _sass
include: ['_pages']
kramdown:
  input: GFM
